.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. groincoin_qt test_groincoin_qt
clean: FORCE
	$(MAKE) -C .. groincoin_qt_clean test_groincoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_groincoin_qt_check
groincoin-qt groincoin-qt.exe: FORCE
	 $(MAKE) -C .. groincoin_qt
